version: "2"
services:
  minetest:
    image: minetest
    ports:
      - "30000/udp:30000/udp"
    volumes:
      - /home/vincent/minetest-data/mods:/home/minetest/minetest-bin/mods:rw
      - /home/vincent/minetest-data/worlds:/home/minetest/worlds:rw
  nextcloud:
    image: nextcloud:12-apache
    ports:
      - "8080:80"
    volumes:
      - /home/vincent/nextcloud/:/var/www/html/
    depends_on:
      - db
  nginx:
    build:
        context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/vincent/ssl/:/etc/nginx/ssl
    restart: always
  db:
    image: mysql
    volumes:
      - /home/vincent/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
  minetest-map:
    image: minetest-map
    volumes:
      - /home/vincent/minetest-data/worlds/the_world/:/opt/world
      - /home/vincent/minetest-tiles:/opt/tiles
    ports:
     - 8081:8080
  # jekyll:
  #   image: jekyll/jekyll:3.7
  #   command: jekyll serve
  #   volumes:
  #     - /home/vincent/jekyll-blog:/srv/jekyll
  #     - /home/vincent/jekyll-blog/vendor/bundle:/usr/local/bundle
  #   ports:
  #     - 4000:4000
